Vagrant.configure("2") do |config|
	config.vm.box = "subutai/windows-installer"
	config.vm.network :forwarded_port, guest: 3389, host: 43389, auto_correct: true
	config.vm.synced_folder ".", "c:"

	config.vm.provider "virtualbox" do |v|
	    v.name = "Subutai Windows Installer Environment"
	    v.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "2"]
	end
end