#!/bin/bash

echo -e "\nGatewayPorts yes" >> /etc/ssh/sshd_config
bash -c "echo 180 > /sys/block/sda/device/timeout"
bash -c "echo 180 > /sys/block/sdb/device/timeout"
pkill -9 snappy
if [ "$(grep "gw.intra.lan" -c /etc/writable/hostname)" == "0" ]; then
	echo "rh`date +%s`.gw.intra.lan" > /etc/writable/hostname
	hostname -F /etc/writable/hostname
fi
snappy install --allow-unauthenticated /home/ubuntu/subutai_4.0.0_amd64.snap
if [ -e "/dev/sdc" ]; then 
disk="/dev/sdc";
else 
disk="/dev/sdb";
fi
/apps/subutai/current/bin/btrfsinit $disk

systemctl stop snappy-autopilot.service
systemctl disable snappy-autopilot.service
systemctl stop snappy-autopilot.timer
systemctl disable snappy-autopilot.timer
mount -o remount,rw /
rm -rf /lib/systemd/system/snappy-autopilot.timer
mount -o remount,ro /
