#!/bin/bash

mkdir /tmp/Subutai

plugin_path=/Users/"${USER}"/Library/Application\ Support/Google/Chrome/External\ Extensions/kpmiofpmlciacjblommkcinncmneeoaa.json

ssh-keygen -R "[localhost]:4567"

function jsonval {
    temp=`echo $json | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w $prop`
    echo ${temp##*|}
}

function download {
	json=`curl -k -s -X GET https://cdn.subut.ai:8338/kurjun/rest/file/info?name=$filename`
	prop='id'
	id=`jsonval`
	if [ -e $target ]; then
		if [ "`md5 $target | awk '{print $4}'`" = "`echo $id | cut -d '.' -f 2`" ]; then :
		else curl -k -o $target https://cdn.subut.ai:8338/kurjun/rest/file/get\?id\=$id
		fi
	else curl -k -o $target https://cdn.subut.ai:8338/kurjun/rest/file/get\?id\=$id
	fi
	if [ "`md5 $target | awk '{print $4}'`" = "`echo $id | cut -d '.' -f 2`" ]; then :
		download
	fi
} 

function install_tuntap {
	target="/tmp/Subutai/tuntap_20150118.pkg"; filename="tuntap_20150118_osx.pkg"; download
	installer -pkg /tmp/Subutai/tuntap_20150118.pkg -target /
}

function install_libssh2 {
	target="/tmp/Subutai/libssh2-1.6.0-0.pkg"; filename="libssh2-1.6.0-0_osx.pkg"; download
	installer -pkg /tmp/Subutai/libssh2-1.6.0-0.pkg -target /
}

function get_p2p {
	target="/Applications/Subutai/p2p"; filename="p2p_osx"; download
	chmod a+x /Applications/Subutai/p2p
}

function get_tray {
	target="/tmp/Subutai/SubutaiTray.tar.gz"; filename="SubutaiTray.app_osx.tar.gz"; download
	/usr/bin/tar -xf /tmp/Subutai/SubutaiTray.tar.gz -C /Applications/Subutai
}

function get_chrome {
	target="/tmp/Subutai/GoogleChrome.tar.gz"; filename="GoogleChrome_osx.tar.gz"; download
	/usr/bin/tar -xf /tmp/Subutai/GoogleChrome.tar.gz -C /Applications
}

function install_plugin {
sudo -u "${USER}" mkdir -p /Users/"${USER}"/Library/Application\ Support/Google/Chrome/External\ Extensions
sudo -u "${USER}" printf '{\n\t"external_update_url": "https://clients2.google.com/service/update2/crx"\n}' > /Users/"${USER}"/Library/Application\ Support/Google/Chrome/External\ Extensions/kpmiofpmlciacjblommkcinncmneeoaa.json
}

function set_path {
sudo -u "${USER}" echo '\nexport PATH="/Applications/Subutai:$PATH"' >> ~/.bash_profile
}

function create_config {
mkdir -p /usr/local/etc/p2p
echo "iptool: /sbin/ifconfig" > /usr/local/etc/p2p/config.yaml
}

function run_services {
launchctl load /Library/LaunchDaemons/io.subutai.p2p.daemon.plist
sudo -u "${USER}" open /Applications/Subutai/SubutaiTray.app
}

if [ -e /dev/tap0 ]; then :
else install_tuntap
fi

if [ -e /usr/local/lib/libssh2.dylib ]; then :
else install_libssh2
fi

get_p2p
get_tray

if [ -e "/Applications/Google Chrome.app" ]; then :
else get_chrome
fi

if [ "`sudo -u "${USER}" grep Subutai ~/.bash_profile`" ];then :; else set_path; fi
if [ -e /usr/local/etc/p2p/config.yaml ]; then :; else create_config; fi
if [ -e plugin_path ]; then :; else install_plugin; fi
if [ -e /Applications/Subutai ]; then run_services; fi

chown -R "${USER}" /Applications/Subutai/
/bin/rm -rf /tmp/Subutai
