#!/bin/bash

vboxmanage="/usr/local/bin/VBoxManage"

ssh-keygen -R [localhost]:4567

if [ -e /Applications/VirtualBox.app ]; then :
else sudo installer -pkg /Applications/Subutai/dist/VirtualBox.pkg -target /
fi

if [ -e /dev/tap0 ]; then :
else sudo installer -pkg /Applications/Subutai/dist/tuntap_20150118.pkg -target /
fi

function import_vm {
sudo -H -u $(users) $vboxmanage import /Applications/Subutai/snappy.ova
sudo -H -u $(users) $vboxmanage modifyvm snappy --cpus 4
sudo -H -u $(users) $vboxmanage modifyvm snappy --memory 4048
sudo -H -u $(users) $vboxmanage modifyvm snappy --nic1 nat
sudo -H -u $(users) $vboxmanage modifyvm snappy --cableconnected1 on
sudo -H -u $(users) $vboxmanage modifyvm snappy --natpf1 "ssh-fwd,tcp,,4567,,22" --natpf1 "https-fwd,tcp,,9999,,8443"
sudo -H -u $(users) $vboxmanage modifyvm snappy --rtcuseutc on
sudo -H -u $(users) $vboxmanage modifyvm snappy --name subutai
sudo -H -u $(users) $vboxmanage startvm --type headless subutai
}

function wait_ssh {
while [ $(sleep 1 | telnet localhost 4567 | grep SSH > /dev/null 2>&1; echo $?) != "0" ]; do
	sleep 1
done
}

function copy_key {
pubkey="$(cat /var/root/.ssh/id_rsa.pub)"
/usr/bin/expect -f - <<EOF
set timeout 30
spawn ssh -o StrictHostKeyChecking=no ubuntu@localhost -p4567 "sudo bash -c 'echo $pubkey >> /home/ubuntu/.ssh/authorized_keys' "
expect "?assword:"
send "ubuntu\r"
expect eof
EOF
}

function install_subutai {
scp -P4567 -o StrictHostKeyChecking=no /Applications/Subutai/scripts/prepare-server /Applications/Subutai/snap/subutai_4.0.0_amd64.snap ubuntu@localhost:~/
ssh -o StrictHostKeyChecking=no ubuntu@localhost -p4567 "sudo /home/ubuntu/prepare-server"
}

function install_management {
scp -P4567 -i /var/root/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@localhost /Applications/Subutai/templates/master-subutai-template_4.0.0_amd64.tar.gz /Applications/Subutai/templates/management-subutai-template_4.0.0_amd64.tar.gz ubuntu@localhost:~/
ssh -i /var/root/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@localhost -p4567 "sudo mv /home/ubuntu/*.gz /mnt/lib/lxc/lxc-data/tmpdir/"
ssh -i /var/root/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@localhost -p4567 "sudo iptables -P INPUT DROP; sudo iptables -P OUTPUT DROP; sudo iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT; sudo iptables -A OUTPUT -p tcp --sport 22 -m state --state ESTABLISHED,RELATED -j ACCEPT"
ssh -i /var/root/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@localhost -p4567 "sudo echo -e 'y' | sudo subutai import master"
ssh -i /var/root/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@localhost -p4567 "sudo echo -e 'y' | sudo subutai import management"
ssh -i /var/root/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@localhost -p4567 "sudo iptables -P INPUT ACCEPT; sudo iptables -P OUTPUT ACCEPT"
}

function set_path {
sudo -H -u $(users) echo 'export PATH="/Applications/Subutai:$PATH"' >> ~/.bash_profile
}

function create_config {
sudo -u $(users) mkdir /usr/local/etc/p2p
sudo -u $(users) echo "iptool: /sbin/ifconfig" > /usr/local/etc/p2p/config.yaml
}

function run_services {
/Applications/Subutai/p2p daemon &>/dev/null &
sudo -u $(users) /Applications/Subutai/SubutaiTray.app/Contents/MacOS/SubutaiTray &
}

if [ "sudo -H -u $(users) $vboxmanage list vms | grep subutai" ]; then
	sudo -H -u $(users) $vboxmanage controlvm subutai poweroff
	sudo -H -u $(users) $vboxmanage unregistervm subutai --delete
	import_vm
else
	import_vm
fi
wait_ssh
if [ -f "/var/root/.ssh/id_rsa.pub" ]; then
	copy_key
else
	ssh-keygen -t rsa -f /var/root/.ssh/id_rsa -q -N ""
	copy_key
fi
install_subutai
install_management
if sudo -u $(users) grep Subutai ~/.bash_profile; then :; else set_path; fi
if [ -e /usr/local/etc/p2p/config.yaml ]; then :; else create_config; fi
run_services
